[
    {
      "name": "EMINEM",
      "day": 4,
      "date": 3,
      "time": 2230,
      "stage": "0",
      "stageId": 3,
      "duration": 1.5,
      "id": 0,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "BRUNO MARS",
      "day": 5,
      "date": 4,
      "time": 2200,
      "stage": "0",
      "stageId": 3,
      "duration": 1.5,
      "id": 1,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "GORILLAZ",
      "day": 7,
      "date": 6,
      "time": 2300,
      "stage": "0",
      "stageId": 3,
      "duration": 1.5,
      "id": 2,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "NICK CAVE & THE BAD SEEDS",
      "day": 6,
      "date": 5,
      "time": 2200,
      "stage": "0",
      "stageId": 3,
      "duration": 1.5,
      "id": 3,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "NINE INCH NAILS",
      "day": 5,
      "date": 4,
      "time": 24,
      "stage": "1",
      "stageId": 2,
      "duration": 1.2,
      "id": 4,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "MASSIVE ATTACK",
      "day": 7,
      "date": 6,
      "time": 100,
      "stage": "0",
      "stageId": 3,
      "duration": 1.5,
      "id": 5,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "DAVID BYRNE",
      "day": 7,
      "date": 6,
      "time": 0,
      "stage": "1",
      "stageId": 2,
      "duration": 1.5,
      "id": 6,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "DUA LIPA",
      "day": 7,
      "date": 6,
      "time": 2000,
      "stage": "0",
      "stageId": 3,
      "duration": 1.5,
      "id": 7,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "NEPHEW",
      "day": 6,
      "date": 5,
      "time": 100,
      "stage": "0",
      "stageId": 3,
      "duration": 1.5,
      "id": 8,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "ALEX VARGAS",
      "day": 6,
      "date": 5,
      "time": 1400,
      "stage": "1",
      "stageId": 2,
      "duration": 1.5,
      "id": 9,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "ANDERSON .PAAK & THE FREE NATIONALS",
      "day": 8,
      "date": 7,
      "time": 130,
      "stage": "1",
      "stageId": 2,
      "duration": 1,
      "id": 10,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "BEN FROST",
      "day": 5,
      "date": 4,
      "time": 1700,
      "stage": "6",
      "stageId": 5,
      "duration": 1.2,
      "id": 11,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "BLACK STAR",
      "day": 5,
      "date": 4,
      "time": 1400,
      "stage": "1",
      "stageId": 2,
      "duration": 1.5,
      "id": 12,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "CHARLOTTE GAINSBOURG",
      "day": 5,
      "date": 4,
      "time": 0,
      "stage": "6",
      "stageId": 5,
      "duration": 1.2,
      "id": 13,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "CV JØRGENSEN",
      "day": 7,
      "date": 6,
      "time": 1630,
      "stage": "1",
      "stageId": 2,
      "duration": 1.5,
      "id": 14,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "DESCENDENTS",
      "day": 6,
      "date": 5,
      "time": 1700,
      "stage": "6",
      "stageId": 5,
      "duration": 1.2,
      "id": 15,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "FEVER RAY",
      "day": 7,
      "date": 6,
      "time": 200,
      "stage": "1",
      "stageId": 2,
      "duration": 1.5,
      "id": 16,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "FIRST AID KIT",
      "day": 5,
      "date": 4,
      "time": 1600,
      "stage": "0",
      "stageId": 3,
      "duration": 1.5,
      "id": 17,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "FLEET FOXES",
      "day": 6,
      "date": 5,
      "time": 1900,
      "stage": "1",
      "stageId": 2,
      "duration": 1.5,
      "id": 18,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "FOUR TET",
      "day": 7,
      "date": 6,
      "time": 0,
      "stage": "4",
      "stageId": 0,
      "duration": 1,
      "id": 19,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "INTERPOL",
      "day": 5,
      "date": 4,
      "time": 1900,
      "stage": "0",
      "stageId": 3,
      "duration": 1.5,
      "id": 20,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "JOEY BADA$$",
      "day": 6,
      "date": 5,
      "time": 2145,
      "stage": "4",
      "stageId": 0,
      "duration": 1,
      "id": 21,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "KHALID",
      "day": 5,
      "date": 4,
      "time": 1900,
      "stage": "1",
      "stageId": 2,
      "duration": 1.5,
      "id": 22,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "MIKE SKINNER & MURKAGE PRESENT TONGA",
      "day": 8,
      "date": 7,
      "time": 200,
      "stage": "4",
      "stageId": 0,
      "duration": 1,
      "id": 23,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "MOGWAI",
      "day": 7,
      "date": 6,
      "time": 2100,
      "stage": "1",
      "stageId": 2,
      "duration": 1.2,
      "id": 24,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "MY BLOODY VALENTINE",
      "day": 6,
      "date": 5,
      "time": 200,
      "stage": "1",
      "stageId": 2,
      "duration": 1.5,
      "id": 25,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "ODESZA",
      "day": 6,
      "date": 5,
      "time": 2100,
      "stage": "1",
      "stageId": 2,
      "duration": 1.5,
      "id": 26,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "PABLO MOSES",
      "day": 6,
      "date": 5,
      "time": 1600,
      "stage": "0",
      "stageId": 3,
      "duration": 1.5,
      "id": 27,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "PARTYNEXTDOOR",
      "day": 4,
      "date": 3,
      "time": 1800,
      "stage": "1",
      "stageId": 2,
      "duration": 1,
      "id": 28,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "ST. VINCENT",
      "day": 4,
      "date": 3,
      "time": 2030,
      "stage": "1",
      "stageId": 2,
      "duration": 1,
      "id": 29,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "STONE SOUR",
      "day": 5,
      "date": 4,
      "time": 2130,
      "stage": "1",
      "stageId": 2,
      "duration": 1.5,
      "id": 30,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "STORMZY",
      "day": 5,
      "date": 4,
      "time": 2345,
      "stage": "1",
      "stageId": 2,
      "duration": 1.5,
      "id": 31,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "THE MINDS OF 99",
      "day": 6,
      "date": 5,
      "time": 1900,
      "stage": "0",
      "stageId": 3,
      "duration": 1.5,
      "id": 32,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "VINCE STAPLES",
      "day": 7,
      "date": 6,
      "time": 2130,
      "stage": "4",
      "stageId": 0,
      "duration": 1,
      "id": 33,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "WHEN SAINTS GO MACHINE",
      "day": 5,
      "date": 4,
      "time": 1600,
      "stage": "1",
      "stageId": 2,
      "duration": 1.5,
      "id": 34,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "ALBERT HAMMOND JR",
      "day": 7,
      "date": 6,
      "time": 1430,
      "stage": "1",
      "stageId": 2,
      "duration": 1.2,
      "id": 35,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "ANDA UNION",
      "day": 6,
      "date": 5,
      "time": 1900,
      "stage": "6",
      "stageId": 5,
      "duration": 1.2,
      "id": 36,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "BABY IN VAIN",
      "day": 7,
      "date": 6,
      "time": 215,
      "stage": "2",
      "stageId": 1,
      "duration": 1,
      "id": 37,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "BCUC",
      "day": 5,
      "date": 4,
      "time": 15,
      "stage": "2",
      "stageId": 1,
      "duration": 1,
      "id": 38,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "BELLY",
      "day": 5,
      "date": 4,
      "time": 1630,
      "stage": "4",
      "stageId": 0,
      "duration": 1,
      "id": 39,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "BENAL",
      "day": 6,
      "date": 5,
      "time": 1600,
      "stage": "1",
      "stageId": 2,
      "duration": 1.5,
      "id": 40,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "BISSE",
      "day": 6,
      "date": 5,
      "time": 2100,
      "stage": "6",
      "stageId": 5,
      "duration": 1.2,
      "id": 41,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "BITORI",
      "day": 6,
      "date": 5,
      "time": 200,
      "stage": "2",
      "stageId": 1,
      "duration": 1,
      "id": 42,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "6LACK",
      "day": 5,
      "date": 4,
      "time": 1800,
      "stage": "4",
      "stageId": 0,
      "duration": 1,
      "id": 43,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "THE BLAZE",
      "day": 4,
      "date": 3,
      "time": 0,
      "stage": "4",
      "stageId": 0,
      "duration": 1,
      "id": 44,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "BLONDE REDHEAD",
      "day": 7,
      "date": 6,
      "time": 2300,
      "stage": "6",
      "stageId": 5,
      "duration": 1.2,
      "id": 45,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "BORIS & MERZBOW",
      "day": 5,
      "date": 4,
      "time": 2300,
      "stage": "6",
      "stageId": 5,
      "duration": 1,
      "id": 46,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "CELESTE",
      "day": 6,
      "date": 5,
      "time": 2330,
      "stage": "3",
      "stageId": 4,
      "duration": 1,
      "id": 47,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "CEZINANDO",
      "day": 5,
      "date": 4,
      "time": 1300,
      "stage": "4",
      "stageId": 0,
      "duration": 1,
      "id": 48,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "CHELSEA MANNING",
      "day": 5,
      "date": 4,
      "time": 1530,
      "stage": "3",
      "stageId": 4,
      "duration": 1,
      "id": 49,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "CHELSEA WOLFE",
      "day": 5,
      "date": 4,
      "time": 1800,
      "stage": "2",
      "stageId": 1,
      "duration": 1,
      "id": 50,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "CLUTCH",
      "day": 4,
      "date": 3,
      "time": 1930,
      "stage": "6",
      "stageId": 5,
      "duration": 1,
      "id": 51,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "COURTNEY MARIE ANDREWS",
      "day": 7,
      "date": 6,
      "time": 1200,
      "stage": "3",
      "stageId": 4,
      "duration": 1,
      "id": 52,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "DANNY BROWN",
      "day": 7,
      "date": 6,
      "time": 1700,
      "stage": "6",
      "stageId": 5,
      "duration": 1.2,
      "id": 53,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "DARK TRANQUILLITY",
      "day": 4,
      "date": 3,
      "time": 2200,
      "stage": "2",
      "stageId": 1,
      "duration": 1,
      "id": 54,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "DE UNDERJORDISKE X FRIBYTTERDRØMME",
      "day": 8,
      "date": 7,
      "time": 100,
      "stage": "6",
      "stageId": 5,
      "duration": 1.2,
      "id": 55,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "DEAD CROSS",
      "day": 6,
      "date": 5,
      "time": 1500,
      "stage": "6",
      "stageId": 5,
      "duration": 1.2,
      "id": 56,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "DEBO BAND",
      "day": 4,
      "date": 3,
      "time": 2130,
      "stage": "6",
      "stageId": 5,
      "duration": 1,
      "id": 57,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "DJ RASHIDA",
      "day": 5,
      "date": 4,
      "time": 2130,
      "stage": "0",
      "stageId": 3,
      "duration": 0.5,
      "id": 58,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "DONA ONETE",
      "day": 5,
      "date": 4,
      "time": 2100,
      "stage": "6",
      "stageId": 5,
      "duration": 1.2,
      "id": 59,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "THE DWARFS OF EAST AGOUZA",
      "day": 5,
      "date": 4,
      "time": 1400,
      "stage": "3",
      "stageId": 4,
      "duration": 1,
      "id": 60,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "EL LEOPARDO",
      "day": 5,
      "date": 4,
      "time": 2230,
      "stage": "4",
      "stageId": 0,
      "duration": 1,
      "id": 61,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "EQUIKNOXX FEAT. SHANIQUE MARIE",
      "day": 6,
      "date": 5,
      "time": 1200,
      "stage": "4",
      "stageId": 0,
      "duration": 1,
      "id": 62,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "GAMELAN SALUKAT",
      "day": 5,
      "date": 4,
      "time": 1200,
      "stage": "6",
      "stageId": 5,
      "duration": 1.2,
      "id": 63,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "HALEY HEYNDERICKX",
      "day": 5,
      "date": 4,
      "time": 1230,
      "stage": "3",
      "stageId": 4,
      "duration": 1,
      "id": 64,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "HEILUNG",
      "day": 6,
      "date": 5,
      "time": 100,
      "stage": "6",
      "stageId": 5,
      "duration": 1.2,
      "id": 65,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "HOUSE GOSPEL CHOIR",
      "day": 7,
      "date": 6,
      "time": 1700,
      "stage": "4",
      "stageId": 0,
      "duration": 1,
      "id": 66,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "THE HUNNA",
      "day": 6,
      "date": 5,
      "time": 1215,
      "stage": "2",
      "stageId": 1,
      "duration": 1,
      "id": 67,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "HVAD",
      "day": 6,
      "date": 5,
      "time": 1800,
      "stage": "3",
      "stageId": 4,
      "duration": 1,
      "id": 68,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "I’M WITH HER",
      "day": 4,
      "date": 3,
      "time": 2015,
      "stage": "2",
      "stageId": 1,
      "duration": 1,
      "id": 69,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "JAMES HOLDEN AND THE ANIMAL SPIRITS",
      "day": 6,
      "date": 5,
      "time": 1745,
      "stage": "4",
      "stageId": 0,
      "duration": 1,
      "id": 70,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "JOHN MAUS",
      "day": 5,
      "date": 4,
      "time": 2000,
      "stage": "2",
      "stageId": 1,
      "duration": 1,
      "id": 71,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "JUANA MOLINA",
      "day": 7,
      "date": 6,
      "time": 1845,
      "stage": "3",
      "stageId": 4,
      "duration": 1,
      "id": 72,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "JUJU & JORDASH",
      "day": 5,
      "date": 4,
      "time": 1430,
      "stage": "4",
      "stageId": 0,
      "duration": 1,
      "id": 73,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "KAKKMADDAFAKKA",
      "day": 4,
      "date": 3,
      "time": 1730,
      "stage": "6",
      "stageId": 5,
      "duration": 1,
      "id": 74,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "KALI UCHIS",
      "day": 7,
      "date": 6,
      "time": 1500,
      "stage": "4",
      "stageId": 0,
      "duration": 1,
      "id": 75,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "KEDR LIVANSKIY",
      "day": 7,
      "date": 6,
      "time": 1900,
      "stage": "4",
      "stageId": 0,
      "duration": 1,
      "id": 76,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "KELLY LEE OWENS",
      "day": 8,
      "date": 7,
      "time": 30,
      "stage": "3",
      "stageId": 4,
      "duration": 1,
      "id": 77,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "KIRSTEN ASTRUP",
      "day": 7,
      "date": 6,
      "time": 1545,
      "stage": "3",
      "stageId": 4,
      "duration": 1,
      "id": 78,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "KOKOKO!",
      "day": 7,
      "date": 6,
      "time": 1900,
      "stage": "6",
      "stageId": 5,
      "duration": 1.2,
      "id": 79,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "LARGE UNIT BRAZIL EDITION",
      "day": 7,
      "date": 6,
      "time": 1500,
      "stage": "6",
      "stageId": 5,
      "duration": 1.2,
      "id": 80,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "LAUREL HALO",
      "day": 6,
      "date": 5,
      "time": 2000,
      "stage": "3",
      "stageId": 4,
      "duration": 1,
      "id": 81,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "LEKHFA",
      "day": 6,
      "date": 5,
      "time": 1430,
      "stage": "3",
      "stageId": 4,
      "duration": 1,
      "id": 82,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "LLNN",
      "day": 7,
      "date": 6,
      "time": 230,
      "stage": "3",
      "stageId": 4,
      "duration": 1,
      "id": 83,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "MADALITSO BAND",
      "day": 4,
      "date": 3,
      "time": 2000,
      "stage": "3",
      "stageId": 4,
      "duration": 1,
      "id": 84,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "MADBALL",
      "day": 7,
      "date": 6,
      "time": 2330,
      "stage": "1",
      "stageId": 2,
      "duration": 1,
      "id": 85,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "MARIBOU STATE",
      "day": 5,
      "date": 4,
      "time": 2030,
      "stage": "4",
      "stageId": 0,
      "duration": 1,
      "id": 86,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "MARLON WILLIAMS",
      "day": 6,
      "date": 5,
      "time": 1300,
      "stage": "6",
      "stageId": 5,
      "duration": 1.2,
      "id": 87,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "MAVI PHOENIX",
      "day": 7,
      "date": 6,
      "time": 1300,
      "stage": "4",
      "stageId": 0,
      "duration": 1,
      "id": 88,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "MHD",
      "day": 8,
      "date": 7,
      "time": 0,
      "stage": "4",
      "stageId": 0,
      "duration": 1,
      "id": 89,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "MINYANTA",
      "day": 6,
      "date": 5,
      "time": 1630,
      "stage": "3",
      "stageId": 4,
      "duration": 1,
      "id": 90,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "MOTORSAV",
      "day": 6,
      "date": 5,
      "time": 215,
      "stage": "3",
      "stageId": 4,
      "duration": 0.75,
      "id": 91,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "MYRKUR: FOLKESANGE",
      "day": 7,
      "date": 6,
      "time": 1700,
      "stage": "3",
      "stageId": 4,
      "duration": 1,
      "id": 92,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "MYRKUR",
      "day": 7,
      "date": 6,
      "time": 13,
      "stage": "2",
      "stageId": 1,
      "duration": 1,
      "id": 93,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "NATHAN FAKE",
      "day": 4,
      "date": 3,
      "time": 2130,
      "stage": "4",
      "stageId": 0,
      "duration": 1,
      "id": 94,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "NELSON CAN",
      "day": 5,
      "date": 4,
      "time": 1900,
      "stage": "6",
      "stageId": 5,
      "duration": 1.2,
      "id": 95,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "NEW GEN",
      "day": 6,
      "date": 5,
      "time": 1400,
      "stage": "4",
      "stageId": 0,
      "duration": 1,
      "id": 96,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "NIHILOXICA",
      "day": 4,
      "date": 3,
      "time": 1715,
      "stage": "4",
      "stageId": 0,
      "duration": 1,
      "id": 97,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "NINES",
      "day": 6,
      "date": 5,
      "time": 1600,
      "stage": "4",
      "stageId": 0,
      "duration": 1,
      "id": 98,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "NYT LIV",
      "day": 6,
      "date": 5,
      "time": 130,
      "stage": "3",
      "stageId": 4,
      "duration": 0.75,
      "id": 99,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "OH SEES",
      "day": 6,
      "date": 5,
      "time": 0,
      "stage": "2",
      "stageId": 1,
      "duration": 1,
      "id": 100,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "OMNI",
      "day": 7,
      "date": 6,
      "time": 1815,
      "stage": "2",
      "stageId": 1,
      "duration": 1,
      "id": 101,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "OND TRO",
      "day": 6,
      "date": 5,
      "time": 300,
      "stage": "3",
      "stageId": 4,
      "duration": 1,
      "id": 102,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "OPERAP",
      "day": 7,
      "date": 6,
      "time": 1300,
      "stage": "6",
      "stageId": 5,
      "duration": 1.2,
      "id": 103,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "OTIM ALPHA",
      "day": 7,
      "date": 6,
      "time": 100,
      "stage": "3",
      "stageId": 4,
      "duration": 1,
      "id": 104,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "PAAL NILSSEN-LOVE'S BRAZIL FUNK IMPRO",
      "day": 5,
      "date": 4,
      "time": 2000,
      "stage": "3",
      "stageId": 4,
      "duration": 1,
      "id": 105,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "PAAL NILSSEN-LOVE'S JAPAN FREE JAZZ AND NOISE",
      "day": 4,
      "date": 3,
      "time": 2200,
      "stage": "3",
      "stageId": 4,
      "duration": 1,
      "id": 106,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "PALM",
      "day": 7,
      "date": 6,
      "time": 2230,
      "stage": "3",
      "stageId": 4,
      "duration": 1,
      "id": 107,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "PETER SOMMER",
      "day": 7,
      "date": 5,
      "time": 1800,
      "stage": "0",
      "stageId": 3,
      "duration": 1.5,
      "id": 108,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "PIGS PIGS PIGS PIGS PIGS PIGS PIGS",
      "day": 4,
      "date": 3,
      "time": 1730,
      "stage": "3",
      "stageId": 4,
      "duration": 1,
      "id": 109,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "PREOCCUPATIONS",
      "day": 5,
      "date": 4,
      "time": 2200,
      "stage": "2",
      "stageId": 1,
      "duration": 1,
      "id": 110,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "RASCASUELOS",
      "day": 7,
      "date": 6,
      "time": 1615,
      "stage": "2",
      "stageId": 1,
      "duration": 1,
      "id": 111,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "REGELBAU PRESENTS CENTRAL + DJ SPORTS + C.K + MANMADE DEEJAY",
      "day": 5,
      "date": 4,
      "time": 2200,
      "stage": "3",
      "stageId": 4,
      "duration": 3,
      "id": 112,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "RICHARD DAWSON BAND",
      "day": 6,
      "date": 5,
      "time": 1815,
      "stage": "2",
      "stageId": 1,
      "duration": 1,
      "id": 113,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "RVG",
      "day": 7,
      "date": 6,
      "time": 1230,
      "stage": "2",
      "stageId": 1,
      "duration": 1,
      "id": 114,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "SACRED PAWS",
      "day": 7,
      "date": 6,
      "time": 2200,
      "stage": "2",
      "stageId": 1,
      "duration": 1,
      "id": 115,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "SAMPHA",
      "day": 6,
      "date": 5,
      "time": 2300,
      "stage": "6",
      "stageId": 5,
      "duration": 1.2,
      "id": 116,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "SANDUNES",
      "day": 6,
      "date": 5,
      "time": 2200,
      "stage": "3",
      "stageId": 4,
      "duration": 1,
      "id": 117,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "(SANDY) ALEX G",
      "day": 6,
      "date": 5,
      "time": 2015,
      "stage": "2",
      "stageId": 1,
      "duration": 1,
      "id": 118,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "SAVEUS",
      "day": 4,
      "date": 3,
      "time": 1800,
      "stage": "0",
      "stageId": 3,
      "duration": 1,
      "id": 119,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "SCOUR",
      "day": 7,
      "date": 6,
      "time": 2015,
      "stage": "2",
      "stageId": 1,
      "duration": 1,
      "id": 120,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "SIGRID",
      "day": 7,
      "date": 6,
      "time": 2130,
      "stage": "6",
      "stageId": 5,
      "duration": 1.2,
      "id": 121,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "ŠIROM",
      "day": 7,
      "date": 6,
      "time": 1345,
      "stage": "3",
      "stageId": 4,
      "duration": 1,
      "id": 122,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "SKELETONWITCH",
      "day": 6,
      "date": 5,
      "time": 1400,
      "stage": "2",
      "stageId": 1,
      "duration": 1,
      "id": 123,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "SLAVES",
      "day": 4,
      "date": 3,
      "time": 1830,
      "stage": "2",
      "stageId": 1,
      "duration": 1,
      "id": 124,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "SLYDIGS",
      "day": 8,
      "date": 7,
      "time": 15,
      "stage": "2",
      "stageId": 1,
      "duration": 1,
      "id": 125,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "SMERZ",
      "day": 5,
      "date": 4,
      "time": 1645,
      "stage": "3",
      "stageId": 4,
      "duration": 1,
      "id": 126,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "STEFFI",
      "day": 4,
      "date": 3,
      "time": 1915,
      "stage": "4",
      "stageId": 0,
      "duration": 1,
      "id": 127,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "STEFFLON DON",
      "day": 6,
      "date": 5,
      "time": 2000,
      "stage": "4",
      "stageId": 0,
      "duration": 1,
      "id": 128,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "SUPER PARQUET",
      "day": 7,
      "date": 6,
      "time": 2030,
      "stage": "3",
      "stageId": 4,
      "duration": 1,
      "id": 129,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "SUPERORGANISM",
      "day": 5,
      "date": 4,
      "time": 1830,
      "stage": "3",
      "stageId": 4,
      "duration": 1,
      "id": 130,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "TOUCHÉ AMORÉ",
      "day": 6,
      "date": 5,
      "time": 1615,
      "stage": "2",
      "stageId": 1,
      "duration": 1,
      "id": 131,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "TUNE-YARDS",
      "day": 5,
      "date": 4,
      "time": 1500,
      "stage": "6",
      "stageId": 5,
      "duration": 1.2,
      "id": 132,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "TURBOLENS",
      "day": 5,
      "date": 4,
      "time": 1200,
      "stage": "2",
      "stageId": 1,
      "duration": 1,
      "id": 133,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "VETO",
      "day": 7,
      "date": 6,
      "time": 1900,
      "stage": "1",
      "stageId": 2,
      "duration": 1.2,
      "id": 134,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "WATAIN",
      "day": 7,
      "date": 6,
      "time": 130,
      "stage": "6",
      "stageId": 5,
      "duration": 1,
      "id": 135,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "THE WEATHER STATION",
      "day": 5,
      "date": 4,
      "time": 1400,
      "stage": "2",
      "stageId": 1,
      "duration": 1,
      "id": 136,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "WILKINSON",
      "day": 6,
      "date": 5,
      "time": 100,
      "stage": "4",
      "stageId": 0,
      "duration": 1,
      "id": 137,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "YASMINE HAMDAN",
      "day": 5,
      "date": 4,
      "time": 1600,
      "stage": "2",
      "stageId": 1,
      "duration": 1,
      "id": 138,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "YASUAKI SHIMIZU",
      "day": 6,
      "date": 5,
      "time": 1230,
      "stage": "3",
      "stageId": 4,
      "duration": 1,
      "id": 139,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "YONAKA",
      "day": 7,
      "date": 6,
      "time": 1415,
      "stage": "2",
      "stageId": 1,
      "duration": 1,
      "id": 140,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "YOUNG FATHERS",
      "day": 6,
      "date": 5,
      "time": 2230,
      "stage": "2",
      "stageId": 1,
      "duration": 1,
      "id": 141,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "Ø [PHASE]",
      "day": 6,
      "date": 5,
      "time": 230,
      "stage": "4",
      "stageId": 0,
      "duration": 1,
      "id": 142,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "ADDISABABABAND",
      "day": 1,
      "date": 0,
      "time": 1700,
      "stage": "7",
      "stageId": 7,
      "duration": 1,
      "id": 143,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "ALBIN LEE MELDAU",
      "day": 2,
      "date": 1,
      "time": 1530,
      "stage": "7",
      "stageId": 7,
      "duration": 1,
      "id": 144,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "ALCABEAN",
      "day": 1,
      "date": 0,
      "time": 2000,
      "stage": "7",
      "stageId": 7,
      "duration": 1,
      "id": 145,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "ARTIGEARDIT",
      "day": 3,
      "date": 2,
      "time": 1930,
      "stage": "5",
      "stageId": 6,
      "duration": 1,
      "id": 146,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "B FROM E",
      "day": 1,
      "date": 0,
      "time": 1830,
      "stage": "5",
      "stageId": 6,
      "duration": 1,
      "id": 147,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "BAIME",
      "day": 1,
      "date": 0,
      "time": 2300,
      "stage": "5",
      "stageId": 6,
      "duration": 1,
      "id": 148,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "CABAL",
      "day": 2,
      "date": 1,
      "time": 2130,
      "stage": "7",
      "stageId": 7,
      "duration": 1,
      "id": 149,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "CLARISSA CONNELLY",
      "day": 1,
      "date": 0,
      "time": 1830,
      "stage": "7",
      "stageId": 7,
      "duration": 1,
      "id": 150,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "CTRLS",
      "day": 2,
      "date": 1,
      "time": 2300,
      "stage": "5",
      "stageId": 6,
      "duration": 1,
      "id": 151,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "DIRT FORGE",
      "day": 1,
      "date": 0,
      "time": 1400,
      "stage": "7",
      "stageId": 7,
      "duration": 1,
      "id": 152,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "ECSTASY IN ORDER",
      "day": 2,
      "date": 1,
      "time": 2130,
      "stage": "5",
      "stageId": 6,
      "duration": 1,
      "id": 153,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "EERA",
      "day": 1,
      "date": 0,
      "time": 1530,
      "stage": "7",
      "stageId": 7,
      "duration": 1,
      "id": 154,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "ELLIS MAY",
      "day": 3,
      "date": 2,
      "time": 1630,
      "stage": "5",
      "stageId": 6,
      "duration": 1,
      "id": 155,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "EMIL KRUSE",
      "day": 1,
      "date": 0,
      "time": 1530,
      "stage": "5",
      "stageId": 6,
      "duration": 1,
      "id": 156,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "FOOL",
      "day": 3,
      "date": 2,
      "time": 1800,
      "stage": "5",
      "stageId": 6,
      "duration": 1,
      "id": 157,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "FRAADS",
      "day": 2,
      "date": 1,
      "time": 1500,
      "stage": "5",
      "stageId": 6,
      "duration": 1,
      "id": 158,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "GOSS",
      "day": 2,
      "date": 1,
      "time": 1800,
      "stage": "5",
      "stageId": 6,
      "duration": 1,
      "id": 159,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "GURLI OCTAVIA",
      "day": 2,
      "date": 1,
      "time": 1400,
      "stage": "7",
      "stageId": 7,
      "duration": 1,
      "id": 160,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "HOLM",
      "day": 3,
      "date": 2,
      "time": 1530,
      "stage": "7",
      "stageId": 7,
      "duration": 1,
      "id": 161,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "IRIS GOLD",
      "day": 3,
      "date": 2,
      "time": 2300,
      "stage": "5",
      "stageId": 6,
      "duration": 1,
      "id": 162,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "JADA",
      "day": 1,
      "date": 0,
      "time": 1400,
      "stage": "5",
      "stageId": 6,
      "duration": 1,
      "id": 163,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "JAKOB OGAWA",
      "day": 3,
      "date": 2,
      "time": 1830,
      "stage": "7",
      "stageId": 7,
      "duration": 1,
      "id": 164,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "KIPPENBERGER",
      "day": 2,
      "date": 1,
      "time": 1700,
      "stage": "7",
      "stageId": 7,
      "duration": 1,
      "id": 165,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "KONNI KASS",
      "day": 3,
      "date": 2,
      "time": 1400,
      "stage": "7",
      "stageId": 7,
      "duration": 1,
      "id": 166,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "LOKE DEPH",
      "day": 2,
      "date": 1,
      "time": 1630,
      "stage": "5",
      "stageId": 6,
      "duration": 1,
      "id": 167,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "LUSTER",
      "day": 2,
      "date": 1,
      "time": 2000,
      "stage": "7",
      "stageId": 7,
      "duration": 1,
      "id": 168,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "LYRA VALENZA",
      "day": 1,
      "date": 0,
      "time": 2000,
      "stage": "5",
      "stageId": 6,
      "duration": 1,
      "id": 169,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "LØD",
      "day": 3,
      "date": 2,
      "time": 2000,
      "stage": "7",
      "stageId": 7,
      "duration": 1,
      "id": 170,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "MARATON",
      "day": 3,
      "date": 2,
      "time": 1700,
      "stage": "7",
      "stageId": 7,
      "duration": 1,
      "id": 171,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "MARSHALL CECIL",
      "day": 3,
      "date": 2,
      "time": 2130,
      "stage": "7",
      "stageId": 7,
      "duration": 1,
      "id": 172,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "MIRIAM BRYANT",
      "day": 1,
      "date": 0,
      "time": 1700,
      "stage": "5",
      "stageId": 6,
      "duration": 1,
      "id": 173,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "MOUNT LIBERATION UNLIMITED",
      "day": 2,
      "date": 1,
      "time": 1930,
      "stage": "5",
      "stageId": 6,
      "duration": 1,
      "id": 174,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "PALE HONEY",
      "day": 2,
      "date": 1,
      "time": 2300,
      "stage": "7",
      "stageId": 7,
      "duration": 1,
      "id": 175,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "ROME IS NOT A TOWN",
      "day": 2,
      "date": 1,
      "time": 1830,
      "stage": "7",
      "stageId": 7,
      "duration": 1,
      "id": 176,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "SASSY 009",
      "day": 1,
      "date": 0,
      "time": 2130,
      "stage": "5",
      "stageId": 6,
      "duration": 1,
      "id": 177,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "SIGMA",
      "day": 3,
      "date": 2,
      "time": 1500,
      "stage": "5",
      "stageId": 6,
      "duration": 1,
      "id": 178,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "SIMON LITTAUER",
      "day": 3,
      "date": 2,
      "time": 2130,
      "stage": "5",
      "stageId": 6,
      "duration": 1,
      "id": 179,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "SISTA BOSSEN",
      "day": 1,
      "date": 0,
      "time": 2130,
      "stage": "7",
      "stageId": 7,
      "duration": 1,
      "id": 180,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "SLÆGT",
      "day": 1,
      "date": 0,
      "time": 2300,
      "stage": "7",
      "stageId": 7,
      "duration": 1,
      "id": 181,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    },
    {
      "name": "TAN",
      "day": 3,
      "date": 2,
      "time": 2300,
      "stage": "7",
      "stageId": 7,
      "duration": 1,
      "id": 182,
      "HeadlineScore": 0,
      "iframe": "",
      "rating": 0
    }
  ];

